### ISSUE TITLE
template bug : angle-brackets.end.template syntax.

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#56] opened 2019-04-07 00:15 UTC
`>>`  keyword.operator.bitwise.shift.cpp  
![image](https://user-images.githubusercontent.com/10380828/55676677-7f7e3280-590b-11e9-8676-430eba9ce04e.png)

![image](https://user-images.githubusercontent.com/10380828/55676692-a50b3c00-590b-11e9-8a83-1ba5c91888d7.png)

I think vsc team should  solve this, maybe.

**Comment by matter123** [comment] 2019-04-07 00:16
Duplicate of #33.

**Closed by matter123** 2019-04-07 00:16 UTC
