### ISSUE TITLE
Header files use the wrong syntax for objective-c

### ISSUE THREAD

**Issue by ashgti** [jeff-hykin/cpp-textmate-grammar#409] opened 2019-10-23 15:51 UTC
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [ ] This bug exists for C++
- [x] This bug exists for Objective-C
- [x] This bug exists for Objective-C++

## The code with a problem is:
```
// From Foundation/NSString.h in Xcode 11.1.

@interface NSString : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>

#pragma mark *** String funnel methods ***

/* NSString primitives. A minimal subclass of NSString just needs to implement these two, along with an init method appropriate for that subclass. We also recommend overriding getCharacters:range: for performance.
 */
@property (readonly) NSUInteger length;
- (unichar)characterAtIndex:(NSUInteger)index;

/* The initializers available to subclasses. See further below for additional init methods.
*/
- (instancetype)init NS_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_DESIGNATED_INITIALIZER;

@end
```

## It looks like:

<img width="1253" alt="Screen Shot 2019-10-23 at 8 49 46 AM" src="https://user-images.githubusercontent.com/22535/67411251-2ce82900-f572-11e9-8777-db39f854894f.png">

Dark+ in VSCode. 

## It should look like:
** description of ideal **

Ideally, .h files should default to 'objcpp' since it has the most complete representation of what can be included in a .h file.

<img width="1229" alt="Screen Shot 2019-10-23 at 8 49 58 AM" src="https://user-images.githubusercontent.com/22535/67411271-36719100-f572-11e9-9342-11c0b561e31d.png">

**Comment by matter123** [comment] 2019-10-23 16:18
This extension does not actually control what language is associated with each file extension. An issue would need to be filed with https://github.com/Microsoft/vscode

Before this procedes there are concerns about compatibility and support.

Objective-C++ support features that are seemingly at odds with C++ features (see https://github.com/jeff-hykin/cpp-textmate-grammar/issues/107#issuecomment-484322434). Do you have any references for the Objective-C++ specification, in particular how conflicts are resolved?

The objective-c and objective-c++ have also fallen behind in feature parity with the c++ grammar. This would need to be rectified before that grammar for headers could be switched, or a large number of files would experience a regression in highlighting.

In the meantime, you can set the file association for header files in `setting.json`

**Comment by jeff-hykin** [comment] 2019-10-23 19:09
Hi @ashgti, what you're saying makes sense, and some syntaxes, like Javascript including JSX, do something similar to what you're saying.

### We've developed the C++ syntax a lot
The first major problem is, the development focus of this repo has been focused on C++. We've completely rewritten the C++ syntax and made the highlighting really extensive and complex. The TextMate parser itself is a very weak/incomplete parser, so we've leveraged the standardized limitations of the C++ syntax to make assumptions that color the code significantly better. (We don't like these assumptions, and there is work being done to replace TextMate with a more powerful tool.)

### Our C++ work can't be imported to Objective-C++ :/ (we've tried)
If we took the C++ syntax and directly injected it into the Objective-C++ syntax, everything would break (and has been broken before). The assumptions we make in C++ don't hold true inside of Objective-C/ Objective-C++. We've tried modifying it, but it essentially requires an entire re-write along with detailed knowledge of the Objective-C++ knowledge (which neither of us have).

### Objective-C++ Syntax is sadly underdeveloped
Because C++ syntax can't be directly imported into Objective-C++, and because of the relatively low number of developers writing Objective-C++ in TextMate-based editors, there have been almost no updates to the Objective-C++ syntax. We have plans to finish a library, finish the C++ syntax, then backport it to C, and then try improving Objective-C, Objective-C++, but we are a long way (+1 year) from that and there's not near as many resources for Objective-C++ as there is C++.

### Objective-C++ isn't a strict superset of C++
As matter123 mentioned, even once a great Objective-C++ syntax is created, C++ has been changing a lot, so much so that Objective-C++ isn't a strict superset, and its possible that a strict superset is impossible.


# Conclusion
If you write a lot of Objective-C / Objective-C++, change your settings to associate `.h` files with Objective-C++. 


#### Note
I'm going to close this issue at the moment, but feel free to continue the conversation and we can reopen it if you feel there is still a problem.

**Closed by jeff-hykin** 2019-10-23 19:09 UTC
Labels: External, Question, 🔍 investigating
