### ISSUE TITLE
Some constructor patterns cause vscode to hang with v1.8.14

### ISSUE THREAD

**Issue by allight** [jeff-hykin/cpp-textmate-grammar#174] opened 2019-05-16 20:48 UTC
When I try to open this file: https://android.googlesource.com/platform/art/+/refs/heads/master/runtime/gc/heap.cc in vscode with the extension installed the entire vscode process will hang.

Repro:
1) Download the art project: `git clone  https://android.googlesource.com/platform/art`
2) code .
3) install the jeff-hykin.better-cpp-syntax extension
3) open the file art/runtime/gc/heap.cc

The entire program will freeze.

This appears to occur even if i disable all other extensions.

VSCode version:
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.16-1rodete1-amd64

Other extensions:
% code . --list-extensions
akamud.vscode-theme-onelight
crazywolf.smali
Equinusocio.vsc-material-theme
llvm-vs-code-extensions.vscode-clangd
ms-vscode.cpptools
PKief.material-icon-theme
ryzngard.vscode-header-source
vscode-icons-team.vscode-icons
vscodevim.vim
waderyan.gitblame
xaver.clang-format
zhuangtongfa.Material-theme

**Comment by matter123** [comment] 2019-05-16 20:56
I am unable to reproduce. Is this with Visual Studio Code v1.34 (April)?

This extension just provides syntax highlighting, no code is ran by `jeff-hykin.better-cpp-syntax` so a performance issue would likely be with `vscode-textmate` Visual Studio Code's textmate grammar parser.

**Comment by matter123** [comment] 2019-05-16 21:10
vscode-textmate struggles as line 265 of `art/runtime/gc/heap.cc`
```
TOKENIZING LINE 265: |          : (kVerifyObjectSupport > kVerifyObjectModeFast) ? kVerifyObjectAllocationStackSize :|

@@scanNext 0: |          : (kVerifyObjectSupport > kVerifyObjectModeFast) ? kVerifyObjectAllocationStackSize :\n|
matched: 10 / 11
  popping BeginEndRule#325 @ cpp.tmLanguage.json:1508 - :
  token: |          |
      * source.cpp
      * meta.block.namespace.cpp
      * meta.body.namespace.cpp
      * meta.block.namespace.cpp
      * meta.body.namespace.cpp
      * meta.function.definition.parameters.cpp
      * meta.function.definition.parameters.cpp
  token: |:|
      * source.cpp
      * meta.block.namespace.cpp
      * meta.body.namespace.cpp
      * meta.block.namespace.cpp
      * meta.body.namespace.cpp
      * meta.function.definition.parameters.cpp
      * meta.function.definition.parameters.cpp
      * keyword.operator.ternary.cpp

@@scanNext 11: | (kVerifyObjectSupport > kVerifyObjectModeFast) ? kVerifyObjectAllocationStackSize :\n|
```

**Comment by allight** [comment] 2019-05-16 21:13
I don't think the length has anything to do with it. I'm able to open larger files without problems (for example art/runtime/thread.cc)

**Comment by matter123** [comment] 2019-05-16 21:15
line 265 is 2 nested ternary expressions inside an initializer list for a constructor

**Comment by matter123** [comment] 2019-05-16 21:19
@jeff-hykin any ideas what could be causing this. the pattern popped off (line 1058) is qualified_type, but that's no longer in play when vscode-textmate stops being responsive a couple of tokens later.

**Comment by matter123** [comment] 2019-05-16 21:35
Subbing variable_name for qualified type did not resolve the issue, nor did removing type_alias.

that leaves
#17, #26, and #158 to check

**Comment by matter123** [comment] 2019-05-16 21:42
This is a regression caused by the fix for #17. Because of #127, the function start pattern was marked as non posessive.

**Comment by jeff-hykin** [comment] 2019-05-17 03:49
Taking a look into this now

**Comment by jeff-hykin** [comment] 2019-05-17 04:44
I pushed a patch for this just now and tested it. Let me know if this is still an issue. @allight 

I'm still going to look at your PR though @matter123

**Closed by jeff-hykin** 2019-05-17 04:44 UTC
Labels: High Priority, 🐛 Bug

**Comment by allight** [comment] 2019-05-17 15:38
Nice it seems to work again.

Thanks all.
