### ISSUE TITLE
missing highlight : union , and maybe struct should know what is inside of it.

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#75] opened 2019-04-10 19:56 UTC
`mingw32\include`   
![image](https://user-images.githubusercontent.com/10380828/55908318-ab4f3000-5c0b-11e9-9c3d-67f41fb74e3a.png)

maybe 
`storage.type.struct.cpp` to `storage.type.union.cpp` works.

and maybe need `meta.block.struct.<a-name>.cpp`

**Comment by matter123** [comment] 2019-04-10 19:56
Duplicate of #72.

**Closed by matter123** 2019-04-10 19:56 UTC

**Comment by peaceshi** [comment] 2019-04-10 20:01
how about union??

**Comment by matter123** [comment] 2019-04-10 20:04
with PR #74 
<img width="351" alt="Screen Shot 2019-04-10 at 1 04 26 PM" src="https://user-images.githubusercontent.com/714007/55909559-35a67e00-5b91-11e9-9f76-1d7fa59e622e.png">
