### ISSUE TITLE
Issue with RefPtr

### ISSUE THREAD

**Issue by JayXon** [jeff-hykin/cpp-textmate-grammar#385] opened 2019-09-05 22:20 UTC
![image](https://user-images.githubusercontent.com/1552641/64387241-38968500-cff0-11e9-84e3-d46acecf2cdd.png)

Code can be found at https://fuchsia.googlesource.com/fuchsia/+/master/zircon/system/core/bootsvc/main.cc#267

**Comment by matter123** [comment] 2019-09-05 23:04
Can you reproduce with the setting `"C_Cpp.enhancedColorization": "Disabled",`?

**Comment by JayXon** [comment] 2019-09-05 23:06
nope
![image](https://user-images.githubusercontent.com/1552641/64389328-16543580-cff7-11e9-9add-a5dd7bb63743.png)

**Comment by matter123** [comment] 2019-09-05 23:07
Closing as duplicate of https://github.com/microsoft/vscode-cpptools/issues/3933

**Closed by matter123** 2019-09-05 23:07 UTC
Labels: Question, Syntax: C++

**Comment by JayXon** [comment] 2019-09-05 23:11
But I was not typing and it stays like that forever?

**Comment by matter123** [comment] 2019-09-05 23:13
Maybe consider filing a separate issue with vscode-cpptools then. If disabling enhancedColorization fixies the issue then the issue lies with vscode-cpptools.

**Comment by JayXon** [comment] 2019-09-05 23:50
Looks like microsoft/vscode-cpptools#3901
