### ISSUE TITLE
Add syntax highlighting to certain file extensions

### ISSUE THREAD

**Issue by psclkhoury** [jeff-hykin/cpp-textmate-grammar#399] opened 2019-10-15 14:33 UTC
Hey,

Is there a way to add syntax highlighting to a certain file type (extension) without setting the language of that file?

The reason for that is we have 'pre-header' files that are parsed and then C++ header files are generated from them. Those pre-header files are mostly C++ code but contain some characters that are not recognized by a C++ parser.

So I would like to have syntax highlighting for those files, without making the associations that all those files are C++ files in vscode, since this will cause the C++ extension to parse them and report a lot of errors in the problems view.

Thanks

**Comment by matter123** [comment] 2019-10-15 15:00
The best option would likely be to create your own [Language Support Extension](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) whose `preinclude.TmLanguage.json` consists of

```json
{
	"$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
	"name": "C++ Pre Include",
	"patterns": [
		{
			"include": "source.cpp"
		}
	],
	"repository": {},
	"scopeName": "source.cpp.pre"
}
```

Alternatively, you can clone this extension and modify package.json to contribute a language that uses the same syntax highlighting but doesn't use the language id of `cpp`, you will also need to provide a language-configuration.json for the new language.

**Comment by jeff-hykin** [comment] 2019-10-15 22:57
I agree with @matter123's suggestions, note that if you clone this repo every time there is an update you'll have to manually pull in the update (which is not the case with the first solution).

Also @matter123 that $schema is nice, I've haven't seen that before.

I'm going to close this since it's not a bug or feature request, but @psclkhoury feel free to continue the conversation.

**Closed by jeff-hykin** 2019-10-15 22:57 UTC

**Comment by psclkhoury** [comment] 2019-10-17 10:53
okay thanks, I will look into your suggestions. I thought that it would be possible just to add a setting to the extension to also contribute to this specific file extension and then the non cpp grammar will just be left without colors.

**Comment by jeff-hykin** [comment] 2019-10-17 12:49
Hmm I'm not quite sure what you mean by the last statement.
In VS Code, every file has a language associated with it (even if the language is plaintext). So to get C++ highlighting without setting the language to cpp, means a new language must be created.

**Comment by psclkhoury** [comment] 2019-10-17 15:11
I meant that instead of making the file association in the settings of vscode:
```
"files.associations": {
    "*.ph": "cpp"
}
```

I could somehow make this associations only in your extension, that way other extensions won't be activated when I open the file.

**Comment by matter123** [comment] 2019-10-17 16:54
The issue with that is that this extension does not actually contribute a language, rather it just provides a new syntax file for the existing language id `cpp`.

Any attempt to provide syntax highlighting without activating other extensions that activate on the `cpp` language. would require contributing a new language.

**Comment by psclkhoury** [comment] 2019-10-28 15:38
I ended up just writing an extension that contributes a language for my specific extension `.ph`, and I just copied the `cpp.tmLanguage.json` from your repository and I only changed the `fileTypes`. I hope that is okay for you? This extension is only for internal use and will not be published to the marketplace.

1 other question, is it necessary to add the `cpp.embedded.*.tmLanguage.json` files to my extension or `cpp.tmLanguage.json` will suffice?

Thanks!

**Comment by matter123** [comment] 2019-10-28 15:48
`cpp.embedded.latex.*` - is no longer being used and needs to be removed
`cpp.embedded.macro.*` - for macros, you can exclude it, if you do not use macros.

**Comment by jeff-hykin** [comment] 2019-10-28 19:26
Yeah, feel free to copy to the code. I'm glad it's being used 👍

**Comment by psclkhoury** [comment] 2019-10-29 07:42
Great thank you a lot for your help!

**Comment by psclkhoury** [comment] 2019-10-29 11:31
Sorry for bothering, but I have one more question.

So all the non standard `c++` in those files come in the form of attributes that are between square brackets. Example:

```c++
[define(GUID, ("85-de3abc24-e8d1-11d6-8295-001083ff1296")]
class [GUID, smart(dll)] SomeClass : public [some_attribute] Base
{
public:
    [attribute] void test() const;
}
```

How can I make the extension ignore those, because when there is too many of them the syntax highlighting gets messed up. I tried to add something similar to the `"cpp_attributes"` and changed the `begin` and `end`. But it looks like it's being parsed as a lambda or something. 

```json
"ph_attributes": {
  "name": "support.other.attribute.cpp",
  "begin": "(\\[)",
  "beginCaptures": {
    "1": {
      "name": "punctuation.section.attribute.begin.cpp"
    }
  },
  "end": "(\\])",
  "endCaptures": {
    "1": {
      "name": "punctuation.section.attribute.end.cpp"
    }
  }
}
```
![image](https://user-images.githubusercontent.com/9846892/67763299-a6d35300-fa47-11e9-9bb2-78b3d74f69a5.png)

I will try to figure it out myself but any tips and guidance would be very appreciated since I have no experience in textmate grammar.

Thank you again!

**Comment by jeff-hykin** [comment] 2019-10-29 12:36
That is going to be a lot lot harder. You'll basically need to fully understand the C++ grammar and how its parsed as well as the exactly where your non-standard C++ is allowed/not-allowed. 

If you're never going to use lambdas then you could disable them. But I doubt that will be the end of the parsing problems. If you just want basic highlighting, you might be better off trying to highlight it with the C syntax.

If you want to dive into the problem we can help, but its probably not going to be a quick fix if thats what you're looking for.

**Comment by psclkhoury** [comment] 2019-10-29 13:21
I just need basic highlighting and lambdas are (usually) not used in those files. I will try to disable lambdas and use the C syntax.

Thanks @jeff-hykin!

**Comment by matter123** [comment] 2019-10-29 17:58
@psclkhoury do your [attributes] ever appear where an expression is expected?

@jeff-hykin lambdas should probably be limited to where expressions are expected.

**Comment by jeff-hykin** [comment] 2019-10-30 02:05
I agree that would probably reduce the number of accidental cases, and also improve performance a bit.

**Comment by psclkhoury** [comment] 2019-10-30 08:50
> @psclkhoury do your [attributes] ever appear where an expression is expected?
> 
@matter123 No they are added before member function/variables. I will show you an example class that has all the attributes that can possibly appear. Btw I disabled the lambdas as @jeff-hykin suggested and now the attributes are correctly highlighted.

This is a full example class, but I don't mind if syntax highlighting is not 100% accurate, what I already have is quite good thanks to you guys.

```c++
// first example
namespace [version] DataModel
{
[define(GUID, ("85-de3abc24-e8d1-11d6-8295-001083ff1296")]
class [GUID, smart(dll, export), ...] SomeClass : public [subsystem(attribute)] Base
{
public:
    [attribute] [[no_discard]] int test(const int i) const 
    {
        // a lambda might appear here
        return _vec[i]; 
    }

    [attribute] print() const { std::cout << '\n'; }

private:
    [attribute] std::vector<int> _vec;
};
} // namespace [version] DataModel

// second example is to show one other non standard keyword
// which is different from all the others because it's not between []
namespace [version] DataModel
{
// this keyword can only appear in namespace scope
// and when it appears, all the following will be standard C++
// without any special attributes
cape
{
template <class T>
class ClassTemplate : public Base
{
public:
    T operator()() const;
};
}
} // namespace [version] DataModel

```

**Comment by jc-gaiaplatform** [comment] 2021-08-23 17:53
Hi everyone - I know I'm a couple of years late but I am creating something similar to @psclkhoury where the language I am building is built on top of C++ and I only need to add a few keywords but would like to preinclude all of the C++ highlighting. Is there an updated way of doing that or is the preinclude.tmLanguage.json that @matter123 mentioned still a good practice? I cannot find any documentation on the matter so any advice would be greatly appreciated @jeff-hykin

**Comment by jeff-hykin** [comment] 2021-09-09 20:25
Sadly the easiest way is to clone the repo and edit the tokens.rb file, and change it to be a new language, and then generate it.

The reason it's hard to just add keywords is because there are many different context that they can belong to. Some key words only show up inside of class definitions, some only show up in lambdas, or in front of variable declarations. Everything depends on contexts. 

So if you're going to going to add a keyword you need to state everywhere that keyword should be included. And sadly it's easier to do that using the repo than with a language injection because there are so many.
