### ISSUE TITLE
some consistent characteristics of highlight

### ISSUE THREAD

**Issue by Wuqiqi123** [jeff-hykin/cpp-textmate-grammar#39] opened 2019-03-20 02:43 UTC
For a class or struct name, guarantee consistency in the whole file.
My vscode define a struct such as in a .cpp file:
![image](https://user-images.githubusercontent.com/37368540/54655362-a90e2000-4afc-11e9-9c45-84947e5def06.png)
I hope the node and MAX can have the same color in the main function.
Can I have some ways to solve this?

**Comment by jeff-hykin** [comment] 2019-03-20 06:33
Sadly, this is well beyond the capabilities of TextMate grammars :( I very much wish there was a way to do this.

The issue is there are no variables/memory inside the parser. It can only look at what is immediately nearby it, and then use that as a hint as to what the thing is. Often times it can only see one line at a time.

Something that I would like to talk to VS Code about is implementing a fully-supported C++ parser like the one used in Xcode. It would be capable of those kinds of colorings.

I'm going to close this issue, but feel free to continue the conversation.

**Closed by jeff-hykin** 2019-03-20 06:33 UTC
Labels: ☠️ provably impossible
