### ISSUE TITLE
error syntax of sizeof in c code

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#213] opened 2019-05-28 05:47 UTC
![image](https://user-images.githubusercontent.com/10380828/58453785-ee7b4900-814e-11e9-9f20-9abc840f6773.png)
![image](https://user-images.githubusercontent.com/10380828/58453794-f804b100-814e-11e9-83d3-dd981139abce.png)

https://github.com/SDL-mirror/SDL/blob/fbfcaf35a10c6f6881dc5696991063010bfc3481/include/SDL_assert.h#L100

**Comment by matter123** [comment] 2019-05-28 17:46
@jeff-hykin are you able to reproduce?

![Screenshot from 2019-05-28 10-45-47](https://user-images.githubusercontent.com/714007/58499856-cfbc8880-8135-11e9-9ea1-bbaedcf3397d.png)

**Comment by jeff-hykin** [comment] 2019-05-28 19:24
I'm also unable to reproduce.
@peaceshi Are you on version `v1.10.0`?
<img width="940" alt="Screen Shot 2019-05-28 at 3 23 40 PM" src="https://user-images.githubusercontent.com/17692058/58506135-9fd4ab80-815c-11e9-9048-bb9867ebee0a.png">

**Comment by peaceshi** [comment] 2019-05-29 05:42
I try to delete all things and reinstall vsc,seems like it is not extension bug.
![image](https://user-images.githubusercontent.com/10380828/58531647-a6732980-8215-11e9-9251-e3da8a1500e7.png)
```
Version: 1.35.0-insider (system setup)
Commit: a429fd13565d3392c87e31228ec9e8a2bf3708d5
Date: 2019-05-28T16:39:09.837Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by jeff-hykin** [comment] 2019-05-29 05:57
Hmm I'll close this because it's not an extension bug. I wonder what version Insider's is using.

**Comment by matter123** [comment] 2019-05-29 06:06
Last I checked v1.8.15

**Closed** 2019-05-29 06:12 UTC
Labels: 🐛 Bug
