### ISSUE TITLE
conditional_context uses $initial_context

### ISSUE THREAD

**Issue by matter123** [jeff-hykin/cpp-textmate-grammar#176] opened 2019-05-18 00:07 UTC
From: https://github.com/microsoft/vscode/issues/73882

Example (C):
```C
int foo() {
    switch(a) {
        case FOO:
            { FileAccessControl.UserFlashAddess = 1; }
        case BAR:
            FileAccessControl.UserFlashAddess = 1;
    };
}
```

conditional_context's only member is $initial_context. that causes items that are valid inside a function context to no longer be valid in a switch statement.

**Comment by jeff-hykin** [comment] 2019-05-18 02:08
I can't reproduce
<img width="655" alt="Screen Shot 2019-05-17 at 9 07 53 PM" src="https://user-images.githubusercontent.com/17692058/57963297-e10cc600-78e7-11e9-96ec-b556a8806655.png">

**Comment by matter123** [comment] 2019-05-18 02:09
it's a C issue. member access in c++ works in any scope.

**Comment by jeff-hykin** [comment] 2019-05-18 03:07
Okay, I pushed a temporary fix for this just now. We can fully fix it once we work on the C syntax.

**Closed** 2019-05-18 03:08 UTC
Labels: C syntax, 🐛 Bug, 🔍 investigating
