### ISSUE TITLE
Regression with strings

### ISSUE THREAD

**Issue by sean-mcmanus** [jeff-hykin/cpp-textmate-grammar#198] opened 2019-05-24 22:27 UTC
```
#include <string>

std::string s = "correct";
std::string s("incorrect");
std::string s("?"); // incorrect

```
Bug1: String in methods aren't correct.
Bug2: String with ? cause the string to not terminate.
Bug3: The 1st std::string appears differently.

![image](https://user-images.githubusercontent.com/19859882/58359359-f62dab80-7e37-11e9-9fd3-2176c201f7b0.png)

**Comment by matter123** [comment] 2019-05-24 23:25
Bug 1 and 2 are fixed in #199
Bug 3 is being tracked in #81, in particular, #71, and possibly #36

**Closed** 2019-05-24 23:47 UTC
Labels: High Priority, Regression, 🔍 investigating

**Comment by jeff-hykin** [comment] 2019-05-24 23:56
Alright the fix is pushed in `v1.9.4`. @sean-mcmanus  

@matter123 I guess in the root $intital_context we will have to have a special pattern that can be either a function definition or a type initialization.

This also pointed out to me that there's another edge case bug with functions with default values.
```
void func(int a = this->is.a.really +  complicated{ "default", "value"}) {
}
``` 
Right now (after this change) the `:function_parameter_context` is only highlighting literals/strings. Ideally the probably_a_parameter pattern would capture the defaulted section and fix it. Right now they're just being matched kind of free-form.

**Comment by alekseyt** [comment] 2019-05-25 21:07
I think "Bug 3" is due to the fact that "string" in "std::string" sometimes categorized as `entity.name.type` now. It also reproduces in return values:

```c++
	static std::string static_id() {
		return "base";
	}

	glm::vec3 _pos;
	glm::vec3 get_pos() {
		return _pos;
	}
```

![image](https://user-images.githubusercontent.com/993454/58374464-39c30b00-7f47-11e9-92a3-fcdc40d6fa29.png)

I guess `std::string s("hello");` is just being parsed as a declaration of function `s` with return type `std::string` in the original report. This declaration is not entirely correct because `"hello"` isn't a valid argument - it's missing type. Correct declaration would look like something like this:

```c++
std::string s(const char *s);
```

Although i'm not sure how to distinguish declaration and function call in cases similar to these:

```c++
std::string s(int);
std::string s(10);
std::string s(mycooltype);
```

Perhaps this is indeed another manifestation of #81. Just wanted to point out that "Bug 3" is probably not really related to namespaces or variables but to return values, this will also be highlighted now:

```c++
	const mycooltype z() {
		
	}
```

![image](https://user-images.githubusercontent.com/993454/58374599-8f98b280-7f49-11e9-891c-c213bf7fc62d.png)

**Comment by matter123** [comment] 2019-05-25 21:19
@alekseyt  Outside of a function body. `A B(C)` is ambiguous without compiling if `B` is declaring a function or a variable of type `A`. Inside a function body, however, function declarations are not allowed and there is no operator between `A` and `B` so `B` cannot be a function call. that just leaves a variable declaration.

This does become ambiguous again with `A * B(C)` and `A & B(C)` those could still be variable declarations where the type is `A*` or `A&` respectively however they could also be a function call to `B` multiplied-by or bitwise-and with a variable `A`.

But yes, in just `A B`, `A` not being tagged as `entity.name.type` is an issue, in particular #71.

**Comment by alekseyt** [comment] 2019-05-25 21:26
@matter123 please also note that `int` is being tagged as `storage.type` rather than `entity.name.type`, so 

```c++
const int z(10);
```

So with embedded types it won't be `entity.name.type` either. Maybe not tagging `B` is a bug, or maybe it's other way around, just my 2c. Just wanted to point out that this specifically related to _return values_, hope this helps.
