### ISSUE TITLE
this keyword not highlighted

### ISSUE THREAD

**Issue by Novakov** [jeff-hykin/cpp-textmate-grammar#83] opened 2019-04-11 05:16 UTC
VS Code 1.33.0
Better C++ Syntax 1.7.5
No other extensions installed and default settings

Code:
```cpp
void ABC::Method()
{
    this->a
}
```

Highlight:
![2019-04-11_07-15-59](https://user-images.githubusercontent.com/420393/55932380-b44efa00-5c29-11e9-88ba-fe09a85c19c4.gif)

**Comment by matter123** [comment] 2019-04-11 05:27
OK, potential fix: https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/Fix-%2383/syntaxes/cpp.tmLanguage.json

![Screenshot from 2019-04-10 22-25-29](https://user-images.githubusercontent.com/714007/55932701-ae342b80-5bdf-11e9-9035-26b943a55b29.png)

**Comment by Novakov** [comment] 2019-04-11 05:35
ok `this` keyword is now working, however:
![image](https://user-images.githubusercontent.com/420393/55933052-3dffc700-5c2c-11e9-83cb-53cad597f8a5.png)

any maybe not related
![image](https://user-images.githubusercontent.com/420393/55933058-4526d500-5c2c-11e9-82eb-71f9693d3f32.png)

**Comment by matter123** [comment] 2019-04-11 05:38
First image is a duplicate of #71.

Did the second image work on 1.7.5 before?

**Comment by Novakov** [comment] 2019-04-11 05:41
First image - ok, thanks

Second image - I reverted to unmodified 1.7.5 and result is the same. (no highlighting after `extern "C"`)

**Comment by matter123** [comment] 2019-04-11 05:44
Ok I'll make a PR the `this`.

The second image is unrelated. Do you mind creating a separate issue?

**Comment by Novakov** [comment] 2019-04-11 05:50
Sure: `extern "C"` reported here: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/85

**Closed** 2019-04-11 05:55 UTC
