### ISSUE TITLE
$reference in generated grammar

### ISSUE THREAD

**Issue by lieene** [jeff-hykin/cpp-textmate-grammar#424] opened 2019-11-25 16:12 UTC
Checklist

- [ ] This bug exists for C++

## The code with a problem is:

https://github.com/jeff-hykin/cpp-textmate-grammar/blob/a0f03bfce2c9eed3fbe33429b00f174a9775c3b6/syntaxes/cpp.tmLanguage.json#L3066

_$reference(directive)_ not replaced by group id

**Comment by matter123** [comment] 2019-12-04 22:12
Duplicate of #355. I did not realize that at the time, thank you for reporting however.

**Closed by matter123** 2019-12-04 22:12 UTC
