### ISSUE TITLE
Bad coloring of final argument name in multi-line argument list

### ISSUE THREAD

**Issue by kylrth** [jeff-hykin/cpp-textmate-grammar#341] opened 2019-08-05 15:30 UTC
## To reproduce

Type this in a C++ header file (e.g. `sample.hpp`) in VS Code:

```cpp
#include <string>

void doThings(std::string line,
              std::string entryMap,   // a comment
              std::string entriesOne,  // another one
              std::string entriesTwo  // strange coloring here
);
```

## Expected

`entriesTwo` should be colored with the same color as the other arguments.

## Actual

`entriesTwo` is colored the same color as the types.

## Screenshot

![badHighlighting](https://user-images.githubusercontent.com/5044802/62475983-c40bc480-b76b-11e9-8500-3c454bba2e42.png)

## Configuration

Extension version: 1.12.21
C/C++ extension version: 0.24.1
VS Code version: 1.37.0-insider (user setup)
Commit: 4a03f7e7eff2560d2e53c029321870514d19a2aa
Date: 2019-08-05T09:34:10.366Z
OS: Windows_NT x64 6.3.9600 (Windows 8)

**Comment by jeff-hykin** [comment] 2019-08-05 16:57
Thanks for posting this. @kylrth The issue is the pattern is looking for a comma or a newline, so the comment on the last one stops it from finding the newline. This should be an easy fix and will probably get fixed in about a week

**Comment by kylrth** [comment] 2019-08-05 17:05
Awesome!

**Closed** 2019-08-07 16:40 UTC
Labels: Syntax: C++, 🐛 Bug
