### ISSUE TITLE
C++ freeze with specific line

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/cpp-textmate-grammar#426] opened 2019-12-04 10:02 UTC
Checklist

- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## This code causes a grammar freeze:
```c++
json_safe_sprintf(msg3, "\":[", atol(row[8]) /*current car id*/, atoi(row[10]) /*ta driver version*/, atol(row[13]) /*exchange_member_id*/, tmp_line2, atol(row[16]) /*group_id*/, row[1] /*login*/, atof(row[17]));

```
From @w-flame in https://github.com/microsoft/vscode/issues/86014
I maximaly shrink code which still represents isuue.
Freeze happens only in C++ mode, if opening in C mode it's OK.
Freeze happens with and witout C++ extensions installed/enabled.
Freeze happens on Mac and PC with current VSCode versions and some previous releases.

**Comment by alexr00** [comment] 2019-12-04 10:05
It actually did finish eventually (>1 min, <2 min) the second time I tried it.

**Comment by jeff-hykin** [comment] 2019-12-04 15:35
With no repeated characters, this is very likely going to be a tough fix :/
Later tonight I'll see if I can pinpoint the cause and, if successful, that should provide insight on the difficulty.

**Comment by matter123** [comment] 2019-12-04 17:21
Perf report
```
/Users/mfosdick/slow.cpp
source.cpp
source.cpp.embedded.macro
requested grammar outside of this repository
requested grammar outside of this repository
total time: 96775.84208899736ms

match failure
pattern name             average time    total time   peak time
source.cpp:5809         4188.354939    96332.164    32609.107
source.cpp:456             0.105843        2.434        0.201
source.cpp:6862            0.050477        1.161        0.121
source.cpp:2108            0.030863        0.710        0.057
source.cpp:10555           0.029804        0.685        0.058
source.cpp:10588           0.028310        0.651        0.055
source.cpp:11953           0.028131        0.647        0.060
source.cpp:13634           0.027513        0.633        0.063
source.cpp:10791           0.027422        0.631        0.067
source.cpp:6235            0.026817        0.617        0.050
source.cpp:3676            0.024879        0.572        0.050
source.cpp:109             0.016540        0.050        0.047
source.cpp:3947            0.016452        0.049        0.046
source.cpp:11866           0.016272        0.049        0.046
source.cpp:2142            0.014675        0.338        0.215
source.cpp:10092           0.009815        0.363        0.184
source.cpp:10870           0.008576        0.043        0.015
source.cpp:3159            0.007379        0.273        0.017
source.cpp:1340            0.006195        0.229        0.014
source.cpp:7121            0.005990        0.036        0.011

matched, not chosen
pattern name             average time    total time   peak time
source.cpp:3873            0.214398        3.002        0.514
source.cpp:12023           0.027861        0.028        0.028
source.cpp:9977            0.025083        0.502        0.216
source.cpp:3933            0.016935        0.423        0.048
source.cpp:11828           0.015889        0.143        0.021
source.cpp:442             0.014562        0.349        0.036
source.cpp:448             0.014057        0.070        0.000
source.cpp:11837           0.013163        0.079        0.019
source.cpp:6901            0.012774        0.077        0.017
source.cpp:12014           0.011789        0.024        0.014
source.cpp:6895            0.008954        0.188        0.019
source.cpp:7923            0.008587        0.155        0.026
source.cpp:10870           0.008576        0.043        0.000
source.cpp:5744            0.008020        0.192        0.015
source.cpp:6900            0.007758        0.093        0.000
source.cpp:11424           0.006818        0.068        0.010
source.cpp:1162            0.006157        0.012        0.006
source.cpp:7121            0.005990        0.036        0.000

matched, chosen
pattern name             average time    total time   peak time
source.cpp:3873            0.057922        0.348        0.088
source.cpp:12023           0.037855        0.038        0.038
source.cpp:7115            0.031801        0.191        0.035
source.cpp:11424           0.017550        0.018        0.018
source.cpp:3933            0.015242        0.091        0.028
source.cpp:11837           0.014997        0.090        0.043
source.cpp:448             0.014057        0.070        0.021
source.cpp:442             0.013435        0.067        0.022
source.cpp:11828           0.012371        0.074        0.015
source.cpp:6900            0.010971        0.066        0.017
source.cpp:12014           0.010475        0.010        0.010
source.cpp:6901            0.010254        0.062        0.015
source.cpp:1162            0.007968        0.064        0.013
source.cpp:12035           0.007505        0.008        0.008
source.cpp:6895            0.007033        0.042        0.008
```

line 5809 is the begin pattern for lambdas

**Comment by w-flame** [comment] 2019-12-06 11:43
I have found another similar code in my project with same effect. But there are usage of this function in other files with no freeze at all. I tried to experiment and found that processing time increases with arguments count and in some point vscode becomes unresponsive at all. Maybe this will help.

**Comment by jeff-hykin** [comment] 2019-12-06 18:36
Fix for this and probably 90% of other cases published with `v1.14.15`, the issue was the lambda function. I added a check to the lambda that stops it from considering `[]`'s that start with `"` or starts with digits/numbers since those are not allowed in a lambda capture.

The issue is actually the string in `json_safe_sprintf(msg3, "\":["`, so reproducing the issue is still possible with a more complex string. TextMate doesn't care that the `[` is inside a string, it tries to match it to a lambda anyways because thats just how it handles matching a single line. The lambda was then having to evaluate the entire rest of the line before failing, and I imagine this failure to match was repeated several times the more parameters there are. The lambda pattern can probably be made more efficient so that it fails quickly, so I'll keep this issue open for now until I can evaluate that.

**Comment by matter123** [comment] 2019-12-06 18:39
> I imagine this failure to match was repeated several times the more parameters there are

There were only three instances where the lambda regex took over 1000ms to execute, at position 0, position 18, and position 23.

**Comment by jeff-hykin** [comment] 2019-12-07 20:28
Hmm that must mean the issue is the performance of the lambda, probably because there are many brackets since it's trying to allow for brackets inside of a capture. We can probably fix that with subgroups or recursive regex.

**Comment by w-flame** [comment] 2020-03-17 08:01
It seems like problem is gone in last versions. Maybe it's time to close?

**Comment by jeff-hykin** [comment] 2020-03-19 18:35
You're right, thanks @w-flame

**Closed by jeff-hykin** 2020-03-19 18:35 UTC
