### ISSUE TITLE
struct highlight bug .

### ISSUE THREAD

**Issue by peaceshi** [jeff-hykin/cpp-textmate-grammar#61] opened 2019-04-07 14:50 UTC
![image](https://user-images.githubusercontent.com/10380828/55685296-00c6db00-5987-11e9-95f0-382f3458e867.png)
![image](https://user-images.githubusercontent.com/10380828/55685310-281da800-5987-11e9-851b-8cc21f1cd05b.png)
```json
        {
            "name": "entity.name.type.struct",
            "scope": [
                "source.cpp entity.name.type.struct" // name of thing you want to color
            ],
            "settings": {
                "foreground":  "#29e6c6", // color you want it to be
                "fontStyle": "", // bold/underline/italics or none
            }
        },

**Comment by matter123** [comment] 2019-04-07 15:38
This is a duplicate of #39. Vscode does single line matching. The grammar has no way of knowing that SYSTEMTIME is a type. fixing this would require vscode switch to a different tokenizer, say tree-sitter or letting the language service provider, provide the tokenization.

**Comment by matter123** [comment] 2019-04-07 16:20
Sorry, I think I was mistaken, only `A B(C)` is ambiguous. `A B` should always be <type> <value>.

**Comment by matter123** [comment] 2019-04-07 20:56
In the expressions:
 1. `A B`
 2. `A B(C)`
 3. `A B{C}`

`A` is always a type
`B` is a always variable in 1 and 3, and either a variable or a function in 2
`C` is a value in 3 and either a type or a value in 2.

`A` should be safe to tag but `B` and `C` are not.

**Comment by jeff-hykin** [comment] 2019-04-07 21:32
@peaceshi Could you add a bit more clarification? 
What would be different if the bug didn't exist? (what tag would be added/removed from which piece of text)

**Comment by jeff-hykin** [comment] 2019-04-10 04:22
@matter123 Do you understand this issue? I'm still not sure what needs to be fixed here.

**Comment by matter123** [comment] 2019-04-10 04:25
`::SYSTEMTIME` is not tagged as a type.

**Comment by matter123** [comment] 2019-04-12 15:46
Closing in favor of #71.

**Closed by matter123** 2019-04-12 15:46 UTC
Labels: Hard, Nearly Impossible :(, ✨ Enhancement, 🔍 investigating
