### ISSUE TITLE
"<variable> * <function>" highlighted incorrectly

### ISSUE THREAD

**Issue by WEGFan** [jeff-hykin/cpp-textmate-grammar#204] opened 2019-05-25 17:02 UTC
VS Code version: 1.34.0
Extension version: 1.9.0 ~ 1.9.5

Sample code
```cpp
int fun() 
{
    return 1;
}

int main()
{
    int a, b; 
    a = b * fun();
    return 0;
}
```
![Snipaste_2019-05-26_01-01-39](https://user-images.githubusercontent.com/7558201/58372570-db4f5a00-7f51-11e9-8f38-400cac577ac8.png)

**Comment by matter123** [comment] 2019-05-25 17:38
Can you describe what you expect the highlighting to be?

**Comment by WEGFan** [comment] 2019-05-25 17:49
"b" and "*" should not be highlighted, it seems that they were treated as a type and a pointer.
![image](https://user-images.githubusercontent.com/7558201/58372961-66335300-7f58-11e9-9335-48cb375c2384.png)
![image](https://user-images.githubusercontent.com/7558201/58372966-84994e80-7f58-11e9-9b22-05dc3d05d380.png)

**Comment by matter123** [comment] 2019-05-25 17:57
Duplicate of #193. I'll try to get a fix in today.

**Closed by matter123** 2019-05-25 17:57 UTC
Labels: 🐛 Bug
