### ISSUE TITLE
Parameter names are not highlighted

### ISSUE THREAD

**Issue by arzaidi** [jeff-hykin/cpp-textmate-grammar#158] opened 2019-05-10 21:49 UTC
I have just started using Visual Studio Code, and installed your extension but it doesn't change anything in C++ syntax highlighting. 
I am using Visual Studio Code - Insiders Version : 1.34.20

Attaching snapshot where you can see that the parameter type and name colors are unchanged.

![Capture](https://user-images.githubusercontent.com/47612466/57558498-e304e100-734b-11e9-87a0-101d5f9c81ba.JPG)

**Comment by matter123** [comment] 2019-05-10 21:51
Vscode insiders is already using 1.8.8 so there should be only minor improvements at the moment. Though that might be a bug.

**Comment by matter123** [comment] 2019-05-10 21:53
Parameters type highlighting is being tracker by #135. We hope to get that merged in tonight.

**Comment by matter123** [comment] 2019-05-10 21:58
Is `what` still white after disabling "Custom C++ Highlighting" and reloading?

**Comment by jeff-hykin** [comment] 2019-05-10 22:05
@arzaidi The extension is the bleeding edge updates to the syntax, kind of like Chrome Canary, or Firefox nightlies. Sometimes there will be a big difference, however VS Code uses the extension to get official update to the syntax once it has proven itself to be stable.

As matter123 pointed out, right now there are not that many differences between the VS Code Insiders release and the Better C++ extension. If you're using the normal VS Code release though its quiet different.

**Comment by jeff-hykin** [comment] 2019-05-10 22:06
You might also need a theme that highlights more pieces of the syntax, since the default VS Code theme highlights very little.

**Comment by matter123** [comment] 2019-05-10 22:18
![Screenshot from 2019-05-10 15-16-13](https://user-images.githubusercontent.com/714007/57559429-94008100-7336-11e9-9e60-5079ae91e4ba.png)

Yeah, the `Dark (Visual Studio)` theme does not have coloring for `variable.parameter`.

With `Dark + (default dark)` you can see that `what` and `throwExcp` are highlighted.
![Screenshot from 2019-05-10 15-17-40](https://user-images.githubusercontent.com/714007/57559470-d9bd4980-7336-11e9-8597-fe790596688c.png)

Closing as this is a theme color issue. See #7 if you want to customize your theme.

**Comment by arzaidi** [comment] 2019-05-13 17:39
Thanks guys. I think there is some other issue here, as when I inspect, my variables are not marked as variables. I assume some different tokenization related extension needed?
![Capture2](https://user-images.githubusercontent.com/47612466/57642095-86d8d180-7584-11e9-85ac-df6555e3bee4.JPG)

**Comment by matter123** [comment] 2019-05-13 17:41
Huh

**Comment by matter123** [comment] 2019-05-13 17:43
Is that the whole file?

**Comment by arzaidi** [comment] 2019-05-13 17:46
no thats not the whole file, it has usual includes and namespace etc on the top

**Comment by jeff-hykin** [comment] 2019-05-13 17:50
If you can link the whole file we'll take a look into it. This is a pretty suprising bug.

**Comment by matter123** [comment] 2019-05-13 18:05
It is marked as `meta.function-call`, are you defining a function while inside a function?

**Comment by arzaidi** [comment] 2019-05-13 18:09
Found the root cause, it is due to the use of unnamed namespace. If you provide a name to the namespace then it works fine. Here is the sample to reproduce:
---------------------------------
#include "sample.h"
namespace
{
void failedToLoadCriticalData(const string& what, bool throwExcp = false)
{
}
}

**Comment by matter123** [comment] 2019-05-13 18:10
Probably the same issue as #72 then. Thanks.

**Comment by matter123** [comment] 2019-05-13 18:29
@arzaidi 
I meant that This and #72 had the same root cause, where the opening pattern expected a space then a `{`, not that is was exactly the same issue. If you want to test the fix for your issue #165 has its syntax file at https://raw.githubusercontent.com/jeff-hykin/cpp-textmate-grammar/fix/%23158/syntaxes/cpp.tmLanguage.json.

**Comment by arzaidi** [comment] 2019-05-13 18:44
great. Thank you guys, I used this file and it fixed the issue.

**Comment by jeff-hykin** [comment] 2019-05-14 16:57
I'll try to get matter123's merged into master in the next 2 days.

**Closed** 2019-05-15 22:11 UTC
Labels: 🐛 Bug
